"use client";
import { FormEvent, useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { useParams } from "next/navigation";
import { apiFetch, PermissionGrant, Project } from "@/lib/api";

const prefixes = ["workspace:", "command:", "erp:"];
export default function ProjectSettingsPage() {
  const { id } = useParams<{ id: string }>(); const projectId = Number(id);
  const [project, setProject] = useState<Project | null>(null); const [grants, setGrants] = useState<PermissionGrant[]>([]);
  const [prefix, setPrefix] = useState("workspace:"); const [value, setValue] = useState(""); const [decision, setDecision] = useState("allow"); const [expiresAt, setExpiresAt] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState("");
  const load = useCallback(async () => { const [p, g] = await Promise.all([apiFetch<Project>(`/projects/${projectId}`), apiFetch<PermissionGrant[]>(`/projects/${projectId}/permissions`)]); setProject(p); setGrants(g); }, [projectId]);
  useEffect(() => { // eslint-disable-next-line react-hooks/set-state-in-effect
    void load().catch((e) => setMessage(e instanceof Error ? e.message : "Could not load permissions"));
  }, [load]);
  const add = async (e: FormEvent) => { e.preventDefault(); setBusy("add"); try { await apiFetch(`/projects/${projectId}/permissions`, { method: "POST", body: JSON.stringify({ resource: `${prefix}${value}`, decision, expires_at: expiresAt ? new Date(expiresAt).toISOString() : null }) }); setValue(""); setExpiresAt(""); setMessage("Permission grant saved."); await load(); } catch (e) { setMessage(e instanceof Error ? e.message : "Could not save permission"); } finally { setBusy(""); } };
  const expire = async (g: PermissionGrant) => { setBusy(g.id); try { await apiFetch(`/projects/${projectId}/permissions/${g.id}`, { method: "PATCH" }); await load(); } catch (e) { setMessage(e instanceof Error ? e.message : "Could not expire permission"); } finally { setBusy(""); } };
  const revoke = async (g: PermissionGrant) => { if (!window.confirm(`Revoke ${g.resource}?`)) return; setBusy(g.id); try { await apiFetch(`/projects/${projectId}/permissions/${g.id}`, { method: "DELETE" }); await load(); } catch (e) { setMessage(e instanceof Error ? e.message : "Could not revoke permission"); } finally { setBusy(""); } };
  return <main className="mx-auto max-w-3xl space-y-6 p-8"><div><Link href={`/projects/${projectId}`} className="text-sm text-blue-600">← Agent</Link><h1 className="mt-2 text-3xl font-bold">{project?.name || "Project"} settings</h1><p className="mt-1 text-gray-500">Manage workspace, command, and ERP grants used by approvals.</p></div><form onSubmit={add} className="space-y-3 rounded-2xl border p-5 dark:border-white/10"><h2 className="text-xl font-semibold">Add grant</h2><div className="flex gap-2"><select value={prefix} onChange={(e) => setPrefix(e.target.value)} className="rounded-lg border px-3 py-2 dark:bg-black">{prefixes.map((p) => <option key={p}>{p}</option>)}</select><input required value={value} onChange={(e) => setValue(e.target.value)} placeholder="resource pattern" className="min-w-0 flex-1 rounded-lg border px-3 py-2 dark:bg-black" /></div><div className="flex flex-wrap gap-3"><select value={decision} onChange={(e) => setDecision(e.target.value)} className="rounded-lg border px-3 py-2 dark:bg-black"><option value="allow">Allow</option><option value="deny">Deny</option></select><input type="datetime-local" value={expiresAt} onChange={(e) => setExpiresAt(e.target.value)} className="rounded-lg border px-3 py-2 dark:bg-black" /><button disabled={!!busy} className="rounded-lg bg-blue-600 px-4 py-2 text-white disabled:opacity-50">Add grant</button></div></form>{message && <p role="status" className="rounded-xl bg-black/5 p-3 text-sm">{message}</p>}<section className="rounded-2xl border p-5 dark:border-white/10"><h2 className="text-xl font-semibold">Current grants</h2><div className="mt-3 divide-y dark:divide-white/10">{grants.map((g) => <article key={g.id} className="flex flex-wrap items-center justify-between gap-3 py-4"><div><code className="text-sm">{g.resource}</code><p className="text-xs text-gray-500">{g.decision} · {g.expires_at ? `expires ${new Date(g.expires_at).toLocaleString()}` : "never expires"}</p></div><div className="flex gap-2"><button disabled={!!busy || (!!g.expires_at && new Date(g.expires_at) <= new Date())} onClick={() => void expire(g)} className="rounded border px-3 py-1.5 text-xs disabled:opacity-40">Expire now</button><button disabled={!!busy} onClick={() => void revoke(g)} className="rounded border border-red-300 px-3 py-1.5 text-xs text-red-700 disabled:opacity-40">Revoke</button></div></article>)}{!grants.length && <p className="py-6 text-sm text-gray-500">No permission grants yet.</p>}</div></section></main>;
}
