"""add_run_attachments_schedule_reliability_deployment_hardening

Revision ID: 1ad7f6dc0ce3
Revises: 20260901_agent_schedules
Create Date: 2026-09-09 16:02:21.090884
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '1ad7f6dc0ce3'
down_revision = '20260901_agent_schedules'
branch_labels = None
depends_on = None


def _table_exists(table_name):
    return sa.inspect(op.get_bind()).has_table(table_name)


def _column_exists(table_name, column_name):
    return column_name in {column["name"] for column in sa.inspect(op.get_bind()).get_columns(table_name)}


def _index_exists(index_name, table_name):
    return index_name in {index["name"] for index in sa.inspect(op.get_bind()).get_indexes(table_name)}


def _foreign_key_name(table_name, local_columns, referred_table):
    for foreign_key in sa.inspect(op.get_bind()).get_foreign_keys(table_name):
        if (foreign_key.get("constrained_columns") == local_columns
                and foreign_key.get("referred_table") == referred_table):
            return foreign_key.get("name")
    return None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if not _table_exists('run_attachments'):
        op.create_table('run_attachments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('uploader_id', sa.Integer(), nullable=True),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('storage_backend', sa.String(length=16), nullable=False),
    sa.Column('processing_state', sa.String(length=24), nullable=False),
    sa.Column('scan_result', sa.String(length=16), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('extraction_error', sa.Text(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('evidence_refs', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
        )
    for index_name, columns in (
        ('ix_run_attachments_content_hash', ['content_hash']),
        ('ix_run_attachments_project_id', ['project_id']),
        ('ix_run_attachments_run_id', ['run_id']),
    ):
        if not _index_exists(index_name, 'run_attachments'):
            op.create_index(op.f(index_name), 'run_attachments', columns, unique=False)
    if not _index_exists('ix_agent_runs_intent', 'agent_runs'):
        op.create_index(op.f('ix_agent_runs_intent'), 'agent_runs', ['intent'], unique=False)
    for column in (
        sa.Column('idempotency_key', sa.String(length=128), nullable=True),
        sa.Column('retry_count', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('max_retries', sa.Integer(), nullable=False, server_default='3'),
        sa.Column('retry_backoff_seconds', sa.Integer(), nullable=False, server_default='60'),
        sa.Column('missed_run_policy', sa.String(length=16), nullable=False, server_default='skip'),
        sa.Column('concurrency_policy', sa.String(length=16), nullable=False, server_default='skip'),
        sa.Column('timeout_seconds', sa.Integer(), nullable=True),
    ):
        if not _column_exists('agent_schedules', column.name):
            op.add_column('agent_schedules', column)
    if not _index_exists('ix_agent_schedules_idempotency_key', 'agent_schedules'):
        op.create_index(op.f('ix_agent_schedules_idempotency_key'), 'agent_schedules', ['idempotency_key'], unique=True)
    for column in (
        sa.Column('smoke_test_result', sa.JSON(), nullable=True),
        sa.Column('prior_artifact_id', sa.String(length=36), nullable=True),
        sa.Column('recovery_state', sa.String(length=24), nullable=True),
    ):
        if not _column_exists('deployments', column.name):
            op.add_column('deployments', column)
    if not _foreign_key_name('deployments', ['prior_artifact_id'], 'artifacts'):
        op.create_foreign_key('fk_deployments_prior_artifact_id_artifacts', 'deployments', 'artifacts', ['prior_artifact_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    foreign_key_name = _foreign_key_name('deployments', ['prior_artifact_id'], 'artifacts')
    if foreign_key_name:
        op.drop_constraint(foreign_key_name, 'deployments', type_='foreignkey')
    op.drop_column('deployments', 'recovery_state')
    op.drop_column('deployments', 'prior_artifact_id')
    op.drop_column('deployments', 'smoke_test_result')
    op.drop_index(op.f('ix_agent_schedules_idempotency_key'), table_name='agent_schedules')
    op.drop_column('agent_schedules', 'timeout_seconds')
    op.drop_column('agent_schedules', 'concurrency_policy')
    op.drop_column('agent_schedules', 'missed_run_policy')
    op.drop_column('agent_schedules', 'retry_backoff_seconds')
    op.drop_column('agent_schedules', 'max_retries')
    op.drop_column('agent_schedules', 'retry_count')
    op.drop_column('agent_schedules', 'idempotency_key')
    op.drop_index(op.f('ix_agent_runs_intent'), table_name='agent_runs')
    op.drop_index(op.f('ix_run_attachments_run_id'), table_name='run_attachments')
    op.drop_index(op.f('ix_run_attachments_project_id'), table_name='run_attachments')
    op.drop_index(op.f('ix_run_attachments_content_hash'), table_name='run_attachments')
    op.drop_table('run_attachments')
    # ### end Alembic commands ###
