"""add_run_attachments_schedule_reliability_deployment_hardening

Revision ID: 1ad7f6dc0ce3
Revises: 20260901_agent_schedules
Create Date: 2026-09-09 16:02:21.090884
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '1ad7f6dc0ce3'
down_revision = '20260901_agent_schedules'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('run_attachments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('uploader_id', sa.Integer(), nullable=True),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('storage_backend', sa.String(length=16), nullable=False),
    sa.Column('processing_state', sa.String(length=24), nullable=False),
    sa.Column('scan_result', sa.String(length=16), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('extraction_error', sa.Text(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('evidence_refs', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_run_attachments_content_hash'), 'run_attachments', ['content_hash'], unique=False)
    op.create_index(op.f('ix_run_attachments_project_id'), 'run_attachments', ['project_id'], unique=False)
    op.create_index(op.f('ix_run_attachments_run_id'), 'run_attachments', ['run_id'], unique=False)
    op.drop_table('checkpoint_migrations')
    op.drop_index(op.f('checkpoints_thread_id_idx'), table_name='checkpoints')
    op.drop_table('checkpoints')
    op.drop_index(op.f('checkpoint_writes_thread_id_idx'), table_name='checkpoint_writes')
    op.drop_table('checkpoint_writes')
    op.drop_index(op.f('checkpoint_blobs_thread_id_idx'), table_name='checkpoint_blobs')
    op.drop_table('checkpoint_blobs')
    op.create_index(op.f('ix_agent_runs_intent'), 'agent_runs', ['intent'], unique=False)
    op.add_column('agent_schedules', sa.Column('idempotency_key', sa.String(length=128), nullable=True))
    op.add_column('agent_schedules', sa.Column('retry_count', sa.Integer(), nullable=False))
    op.add_column('agent_schedules', sa.Column('max_retries', sa.Integer(), nullable=False))
    op.add_column('agent_schedules', sa.Column('retry_backoff_seconds', sa.Integer(), nullable=False))
    op.add_column('agent_schedules', sa.Column('missed_run_policy', sa.String(length=16), nullable=False))
    op.add_column('agent_schedules', sa.Column('concurrency_policy', sa.String(length=16), nullable=False))
    op.add_column('agent_schedules', sa.Column('timeout_seconds', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_agent_schedules_idempotency_key'), 'agent_schedules', ['idempotency_key'], unique=True)
    op.add_column('deployments', sa.Column('smoke_test_result', sa.JSON(), nullable=True))
    op.add_column('deployments', sa.Column('prior_artifact_id', sa.String(length=36), nullable=True))
    op.add_column('deployments', sa.Column('recovery_state', sa.String(length=24), nullable=True))
    op.create_foreign_key(None, 'deployments', 'artifacts', ['prior_artifact_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'deployments', type_='foreignkey')
    op.drop_column('deployments', 'recovery_state')
    op.drop_column('deployments', 'prior_artifact_id')
    op.drop_column('deployments', 'smoke_test_result')
    op.drop_index(op.f('ix_agent_schedules_idempotency_key'), table_name='agent_schedules')
    op.drop_column('agent_schedules', 'timeout_seconds')
    op.drop_column('agent_schedules', 'concurrency_policy')
    op.drop_column('agent_schedules', 'missed_run_policy')
    op.drop_column('agent_schedules', 'retry_backoff_seconds')
    op.drop_column('agent_schedules', 'max_retries')
    op.drop_column('agent_schedules', 'retry_count')
    op.drop_column('agent_schedules', 'idempotency_key')
    op.drop_index(op.f('ix_agent_runs_intent'), table_name='agent_runs')
    op.create_table('checkpoint_blobs',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('channel', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('version', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('blob', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'channel', 'version', name=op.f('checkpoint_blobs_pkey'))
    )
    op.create_index(op.f('checkpoint_blobs_thread_id_idx'), 'checkpoint_blobs', ['thread_id'], unique=False)
    op.create_table('checkpoint_writes',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('checkpoint_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('idx', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('channel', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('blob', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('task_path', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', 'task_id', 'idx', name=op.f('checkpoint_writes_pkey'))
    )
    op.create_index(op.f('checkpoint_writes_thread_id_idx'), 'checkpoint_writes', ['thread_id'], unique=False)
    op.create_table('checkpoints',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('checkpoint_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('parent_checkpoint_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('checkpoint', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', name=op.f('checkpoints_pkey'))
    )
    op.create_index(op.f('checkpoints_thread_id_idx'), 'checkpoints', ['thread_id'], unique=False)
    op.create_table('checkpoint_migrations',
    sa.Column('v', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('v', name=op.f('checkpoint_migrations_pkey'))
    )
    op.drop_index(op.f('ix_run_attachments_run_id'), table_name='run_attachments')
    op.drop_index(op.f('ix_run_attachments_project_id'), table_name='run_attachments')
    op.drop_index(op.f('ix_run_attachments_content_hash'), table_name='run_attachments')
    op.drop_table('run_attachments')
    # ### end Alembic commands ###
